JAX is a library for array-oriented numerical computation (à la NumPy), with automatic differentiation and JIT compilation to enable high-performance machine learning research.

(D:\a27_YEARS_OLD\pyspark\venv)

In [1]:
from jax import numpy as np

In [2]:
import jax

 python -m pip install --upgrade pip

In [3]:
import jax.numpy as jnp

# Create a JAX array
x = jnp.array([1, 2, 3])

# Basic operations
y = jnp.array([4, 5, 6])
print(jnp.add(x, y))  # Output: [5 7 9]
print(jnp.multiply(x, y))  # Output: [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [4]:
import jax

# Define a function
def my_function(x):
    return jnp.sin(x)

# Compute the gradient
x = 2.0
grad = jax.grad(my_function)(x)
print(grad)  # Output: 0.9092974268256817

-0.41614684


In [6]:
import jax.numpy as jnp

# Create a JAX array
x = jnp.array([1, 2, 3])

# Vectorized operation
y = jnp.sin(x)
print(y)  # Output: [0.84147096 0.90929743 0.14112001]

# Broadcasting
z = jnp.array([2, 2, 2])
print(x + z)  # Output: [3 4 5]

[0.84147096 0.9092974  0.14112   ]
[3 4 5]


In [7]:
import jax
import jax.numpy as jnp

# Define a function
def my_function(x):
    return jnp.sin(x)

# JIT compile the function
my_function_jit = jax.jit(my_function)

# Run the JIT compiled function
x = 2.0
result = my_function_jit(x)
print(result)  # Output: 0.9092974268256817

0.9092974
